services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: on-failure
    ports:
      - "8085:8080"
      - "50000:50000"
    networks:
      - devops
    
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - devops

networks:
  devops:
    driver: bridge
    name: devops